// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package org.jombies.server;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClientMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .org.jombies.server.ClientMessage.MessageType type = 1;
    boolean hasType();
    org.jombies.server.Messages.ClientMessage.MessageType getType();
    
    // optional .org.jombies.server.ClientMessage.ShootDir shootDie = 2;
    boolean hasShootDie();
    org.jombies.server.Messages.ClientMessage.ShootDir getShootDie();
    org.jombies.server.Messages.ClientMessage.ShootDirOrBuilder getShootDieOrBuilder();
    
    // optional .org.jombies.server.ClientMessage.ChangeDirMessage chDir = 3;
    boolean hasChDir();
    org.jombies.server.Messages.ClientMessage.ChangeDirMessage getChDir();
    org.jombies.server.Messages.ClientMessage.ChangeDirMessageOrBuilder getChDirOrBuilder();
  }
  public static final class ClientMessage extends
      com.google.protobuf.GeneratedMessage
      implements ClientMessageOrBuilder {
    // Use ClientMessage.newBuilder() to construct.
    private ClientMessage(Builder builder) {
      super(builder);
    }
    private ClientMessage(boolean noInit) {}
    
    private static final ClientMessage defaultInstance;
    public static ClientMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public ClientMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.jombies.server.Messages.internal_static_org_jombies_server_ClientMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.jombies.server.Messages.internal_static_org_jombies_server_ClientMessage_fieldAccessorTable;
    }
    
    public enum MessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      CHANGE_DIR(0, 1),
      SHOOT(1, 2),
      RELOADING(2, 3),
      ;
      
      public static final int CHANGE_DIR_VALUE = 1;
      public static final int SHOOT_VALUE = 2;
      public static final int RELOADING_VALUE = 3;
      
      
      public final int getNumber() { return value; }
      
      public static MessageType valueOf(int value) {
        switch (value) {
          case 1: return CHANGE_DIR;
          case 2: return SHOOT;
          case 3: return RELOADING;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
              public MessageType findValueByNumber(int number) {
                return MessageType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.jombies.server.Messages.ClientMessage.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final MessageType[] VALUES = {
        CHANGE_DIR, SHOOT, RELOADING, 
      };
      
      public static MessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private MessageType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:org.jombies.server.ClientMessage.MessageType)
    }
    
    public interface DirectionOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required int32 dX = 1;
      boolean hasDX();
      int getDX();
      
      // required int32 dy = 2;
      boolean hasDy();
      int getDy();
      
      // required int32 x = 3;
      boolean hasX();
      int getX();
      
      // required int32 y = 4;
      boolean hasY();
      int getY();
    }
    public static final class Direction extends
        com.google.protobuf.GeneratedMessage
        implements DirectionOrBuilder {
      // Use Direction.newBuilder() to construct.
      private Direction(Builder builder) {
        super(builder);
      }
      private Direction(boolean noInit) {}
      
      private static final Direction defaultInstance;
      public static Direction getDefaultInstance() {
        return defaultInstance;
      }
      
      public Direction getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.jombies.server.Messages.internal_static_org_jombies_server_ClientMessage_Direction_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.jombies.server.Messages.internal_static_org_jombies_server_ClientMessage_Direction_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required int32 dX = 1;
      public static final int DX_FIELD_NUMBER = 1;
      private int dX_;
      public boolean hasDX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getDX() {
        return dX_;
      }
      
      // required int32 dy = 2;
      public static final int DY_FIELD_NUMBER = 2;
      private int dy_;
      public boolean hasDy() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getDy() {
        return dy_;
      }
      
      // required int32 x = 3;
      public static final int X_FIELD_NUMBER = 3;
      private int x_;
      public boolean hasX() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getX() {
        return x_;
      }
      
      // required int32 y = 4;
      public static final int Y_FIELD_NUMBER = 4;
      private int y_;
      public boolean hasY() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getY() {
        return y_;
      }
      
      private void initFields() {
        dX_ = 0;
        dy_ = 0;
        x_ = 0;
        y_ = 0;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasDX()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasDy()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasX()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasY()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, dX_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, dy_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt32(3, x_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeInt32(4, y_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, dX_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, dy_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, x_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, y_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static org.jombies.server.Messages.ClientMessage.Direction parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.jombies.server.Messages.ClientMessage.Direction parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.jombies.server.Messages.ClientMessage.Direction parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.jombies.server.Messages.ClientMessage.Direction parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.jombies.server.Messages.ClientMessage.Direction parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.jombies.server.Messages.ClientMessage.Direction parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static org.jombies.server.Messages.ClientMessage.Direction parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.jombies.server.Messages.ClientMessage.Direction parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.jombies.server.Messages.ClientMessage.Direction parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.jombies.server.Messages.ClientMessage.Direction parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.jombies.server.Messages.ClientMessage.Direction prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements org.jombies.server.Messages.ClientMessage.DirectionOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.jombies.server.Messages.internal_static_org_jombies_server_ClientMessage_Direction_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.jombies.server.Messages.internal_static_org_jombies_server_ClientMessage_Direction_fieldAccessorTable;
        }
        
        // Construct using org.jombies.server.Messages.ClientMessage.Direction.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          dX_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          dy_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          x_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          y_ = 0;
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.jombies.server.Messages.ClientMessage.Direction.getDescriptor();
        }
        
        public org.jombies.server.Messages.ClientMessage.Direction getDefaultInstanceForType() {
          return org.jombies.server.Messages.ClientMessage.Direction.getDefaultInstance();
        }
        
        public org.jombies.server.Messages.ClientMessage.Direction build() {
          org.jombies.server.Messages.ClientMessage.Direction result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private org.jombies.server.Messages.ClientMessage.Direction buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          org.jombies.server.Messages.ClientMessage.Direction result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public org.jombies.server.Messages.ClientMessage.Direction buildPartial() {
          org.jombies.server.Messages.ClientMessage.Direction result = new org.jombies.server.Messages.ClientMessage.Direction(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.dX_ = dX_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.dy_ = dy_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.x_ = x_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.y_ = y_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.jombies.server.Messages.ClientMessage.Direction) {
            return mergeFrom((org.jombies.server.Messages.ClientMessage.Direction)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(org.jombies.server.Messages.ClientMessage.Direction other) {
          if (other == org.jombies.server.Messages.ClientMessage.Direction.getDefaultInstance()) return this;
          if (other.hasDX()) {
            setDX(other.getDX());
          }
          if (other.hasDy()) {
            setDy(other.getDy());
          }
          if (other.hasX()) {
            setX(other.getX());
          }
          if (other.hasY()) {
            setY(other.getY());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasDX()) {
            
            return false;
          }
          if (!hasDy()) {
            
            return false;
          }
          if (!hasX()) {
            
            return false;
          }
          if (!hasY()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                dX_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                dy_ = input.readInt32();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                x_ = input.readInt32();
                break;
              }
              case 32: {
                bitField0_ |= 0x00000008;
                y_ = input.readInt32();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required int32 dX = 1;
        private int dX_ ;
        public boolean hasDX() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public int getDX() {
          return dX_;
        }
        public Builder setDX(int value) {
          bitField0_ |= 0x00000001;
          dX_ = value;
          onChanged();
          return this;
        }
        public Builder clearDX() {
          bitField0_ = (bitField0_ & ~0x00000001);
          dX_ = 0;
          onChanged();
          return this;
        }
        
        // required int32 dy = 2;
        private int dy_ ;
        public boolean hasDy() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public int getDy() {
          return dy_;
        }
        public Builder setDy(int value) {
          bitField0_ |= 0x00000002;
          dy_ = value;
          onChanged();
          return this;
        }
        public Builder clearDy() {
          bitField0_ = (bitField0_ & ~0x00000002);
          dy_ = 0;
          onChanged();
          return this;
        }
        
        // required int32 x = 3;
        private int x_ ;
        public boolean hasX() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public int getX() {
          return x_;
        }
        public Builder setX(int value) {
          bitField0_ |= 0x00000004;
          x_ = value;
          onChanged();
          return this;
        }
        public Builder clearX() {
          bitField0_ = (bitField0_ & ~0x00000004);
          x_ = 0;
          onChanged();
          return this;
        }
        
        // required int32 y = 4;
        private int y_ ;
        public boolean hasY() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        public int getY() {
          return y_;
        }
        public Builder setY(int value) {
          bitField0_ |= 0x00000008;
          y_ = value;
          onChanged();
          return this;
        }
        public Builder clearY() {
          bitField0_ = (bitField0_ & ~0x00000008);
          y_ = 0;
          onChanged();
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:org.jombies.server.ClientMessage.Direction)
      }
      
      static {
        defaultInstance = new Direction(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:org.jombies.server.ClientMessage.Direction)
    }
    
    public interface ChangeDirMessageOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required bool isMoving = 1;
      boolean hasIsMoving();
      boolean getIsMoving();
      
      // optional .org.jombies.server.ClientMessage.Direction dir = 2;
      boolean hasDir();
      org.jombies.server.Messages.ClientMessage.Direction getDir();
      org.jombies.server.Messages.ClientMessage.DirectionOrBuilder getDirOrBuilder();
    }
    public static final class ChangeDirMessage extends
        com.google.protobuf.GeneratedMessage
        implements ChangeDirMessageOrBuilder {
      // Use ChangeDirMessage.newBuilder() to construct.
      private ChangeDirMessage(Builder builder) {
        super(builder);
      }
      private ChangeDirMessage(boolean noInit) {}
      
      private static final ChangeDirMessage defaultInstance;
      public static ChangeDirMessage getDefaultInstance() {
        return defaultInstance;
      }
      
      public ChangeDirMessage getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.jombies.server.Messages.internal_static_org_jombies_server_ClientMessage_ChangeDirMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.jombies.server.Messages.internal_static_org_jombies_server_ClientMessage_ChangeDirMessage_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required bool isMoving = 1;
      public static final int ISMOVING_FIELD_NUMBER = 1;
      private boolean isMoving_;
      public boolean hasIsMoving() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public boolean getIsMoving() {
        return isMoving_;
      }
      
      // optional .org.jombies.server.ClientMessage.Direction dir = 2;
      public static final int DIR_FIELD_NUMBER = 2;
      private org.jombies.server.Messages.ClientMessage.Direction dir_;
      public boolean hasDir() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public org.jombies.server.Messages.ClientMessage.Direction getDir() {
        return dir_;
      }
      public org.jombies.server.Messages.ClientMessage.DirectionOrBuilder getDirOrBuilder() {
        return dir_;
      }
      
      private void initFields() {
        isMoving_ = false;
        dir_ = org.jombies.server.Messages.ClientMessage.Direction.getDefaultInstance();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasIsMoving()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (hasDir()) {
          if (!getDir().isInitialized()) {
            memoizedIsInitialized = 0;
            return false;
          }
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBool(1, isMoving_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeMessage(2, dir_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(1, isMoving_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, dir_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static org.jombies.server.Messages.ClientMessage.ChangeDirMessage parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.jombies.server.Messages.ClientMessage.ChangeDirMessage parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.jombies.server.Messages.ClientMessage.ChangeDirMessage parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.jombies.server.Messages.ClientMessage.ChangeDirMessage parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.jombies.server.Messages.ClientMessage.ChangeDirMessage parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.jombies.server.Messages.ClientMessage.ChangeDirMessage parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static org.jombies.server.Messages.ClientMessage.ChangeDirMessage parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.jombies.server.Messages.ClientMessage.ChangeDirMessage parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.jombies.server.Messages.ClientMessage.ChangeDirMessage parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.jombies.server.Messages.ClientMessage.ChangeDirMessage parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.jombies.server.Messages.ClientMessage.ChangeDirMessage prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements org.jombies.server.Messages.ClientMessage.ChangeDirMessageOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.jombies.server.Messages.internal_static_org_jombies_server_ClientMessage_ChangeDirMessage_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.jombies.server.Messages.internal_static_org_jombies_server_ClientMessage_ChangeDirMessage_fieldAccessorTable;
        }
        
        // Construct using org.jombies.server.Messages.ClientMessage.ChangeDirMessage.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getDirFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          isMoving_ = false;
          bitField0_ = (bitField0_ & ~0x00000001);
          if (dirBuilder_ == null) {
            dir_ = org.jombies.server.Messages.ClientMessage.Direction.getDefaultInstance();
          } else {
            dirBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.jombies.server.Messages.ClientMessage.ChangeDirMessage.getDescriptor();
        }
        
        public org.jombies.server.Messages.ClientMessage.ChangeDirMessage getDefaultInstanceForType() {
          return org.jombies.server.Messages.ClientMessage.ChangeDirMessage.getDefaultInstance();
        }
        
        public org.jombies.server.Messages.ClientMessage.ChangeDirMessage build() {
          org.jombies.server.Messages.ClientMessage.ChangeDirMessage result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private org.jombies.server.Messages.ClientMessage.ChangeDirMessage buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          org.jombies.server.Messages.ClientMessage.ChangeDirMessage result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public org.jombies.server.Messages.ClientMessage.ChangeDirMessage buildPartial() {
          org.jombies.server.Messages.ClientMessage.ChangeDirMessage result = new org.jombies.server.Messages.ClientMessage.ChangeDirMessage(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.isMoving_ = isMoving_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          if (dirBuilder_ == null) {
            result.dir_ = dir_;
          } else {
            result.dir_ = dirBuilder_.build();
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.jombies.server.Messages.ClientMessage.ChangeDirMessage) {
            return mergeFrom((org.jombies.server.Messages.ClientMessage.ChangeDirMessage)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(org.jombies.server.Messages.ClientMessage.ChangeDirMessage other) {
          if (other == org.jombies.server.Messages.ClientMessage.ChangeDirMessage.getDefaultInstance()) return this;
          if (other.hasIsMoving()) {
            setIsMoving(other.getIsMoving());
          }
          if (other.hasDir()) {
            mergeDir(other.getDir());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasIsMoving()) {
            
            return false;
          }
          if (hasDir()) {
            if (!getDir().isInitialized()) {
              
              return false;
            }
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                isMoving_ = input.readBool();
                break;
              }
              case 18: {
                org.jombies.server.Messages.ClientMessage.Direction.Builder subBuilder = org.jombies.server.Messages.ClientMessage.Direction.newBuilder();
                if (hasDir()) {
                  subBuilder.mergeFrom(getDir());
                }
                input.readMessage(subBuilder, extensionRegistry);
                setDir(subBuilder.buildPartial());
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required bool isMoving = 1;
        private boolean isMoving_ ;
        public boolean hasIsMoving() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public boolean getIsMoving() {
          return isMoving_;
        }
        public Builder setIsMoving(boolean value) {
          bitField0_ |= 0x00000001;
          isMoving_ = value;
          onChanged();
          return this;
        }
        public Builder clearIsMoving() {
          bitField0_ = (bitField0_ & ~0x00000001);
          isMoving_ = false;
          onChanged();
          return this;
        }
        
        // optional .org.jombies.server.ClientMessage.Direction dir = 2;
        private org.jombies.server.Messages.ClientMessage.Direction dir_ = org.jombies.server.Messages.ClientMessage.Direction.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            org.jombies.server.Messages.ClientMessage.Direction, org.jombies.server.Messages.ClientMessage.Direction.Builder, org.jombies.server.Messages.ClientMessage.DirectionOrBuilder> dirBuilder_;
        public boolean hasDir() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public org.jombies.server.Messages.ClientMessage.Direction getDir() {
          if (dirBuilder_ == null) {
            return dir_;
          } else {
            return dirBuilder_.getMessage();
          }
        }
        public Builder setDir(org.jombies.server.Messages.ClientMessage.Direction value) {
          if (dirBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            dir_ = value;
            onChanged();
          } else {
            dirBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        public Builder setDir(
            org.jombies.server.Messages.ClientMessage.Direction.Builder builderForValue) {
          if (dirBuilder_ == null) {
            dir_ = builderForValue.build();
            onChanged();
          } else {
            dirBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        public Builder mergeDir(org.jombies.server.Messages.ClientMessage.Direction value) {
          if (dirBuilder_ == null) {
            if (((bitField0_ & 0x00000002) == 0x00000002) &&
                dir_ != org.jombies.server.Messages.ClientMessage.Direction.getDefaultInstance()) {
              dir_ =
                org.jombies.server.Messages.ClientMessage.Direction.newBuilder(dir_).mergeFrom(value).buildPartial();
            } else {
              dir_ = value;
            }
            onChanged();
          } else {
            dirBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        public Builder clearDir() {
          if (dirBuilder_ == null) {
            dir_ = org.jombies.server.Messages.ClientMessage.Direction.getDefaultInstance();
            onChanged();
          } else {
            dirBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        public org.jombies.server.Messages.ClientMessage.Direction.Builder getDirBuilder() {
          bitField0_ |= 0x00000002;
          onChanged();
          return getDirFieldBuilder().getBuilder();
        }
        public org.jombies.server.Messages.ClientMessage.DirectionOrBuilder getDirOrBuilder() {
          if (dirBuilder_ != null) {
            return dirBuilder_.getMessageOrBuilder();
          } else {
            return dir_;
          }
        }
        private com.google.protobuf.SingleFieldBuilder<
            org.jombies.server.Messages.ClientMessage.Direction, org.jombies.server.Messages.ClientMessage.Direction.Builder, org.jombies.server.Messages.ClientMessage.DirectionOrBuilder> 
            getDirFieldBuilder() {
          if (dirBuilder_ == null) {
            dirBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                org.jombies.server.Messages.ClientMessage.Direction, org.jombies.server.Messages.ClientMessage.Direction.Builder, org.jombies.server.Messages.ClientMessage.DirectionOrBuilder>(
                    dir_,
                    getParentForChildren(),
                    isClean());
            dir_ = null;
          }
          return dirBuilder_;
        }
        
        // @@protoc_insertion_point(builder_scope:org.jombies.server.ClientMessage.ChangeDirMessage)
      }
      
      static {
        defaultInstance = new ChangeDirMessage(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:org.jombies.server.ClientMessage.ChangeDirMessage)
    }
    
    public interface ShootDirOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required .org.jombies.server.ClientMessage.Direction dir = 1;
      boolean hasDir();
      org.jombies.server.Messages.ClientMessage.Direction getDir();
      org.jombies.server.Messages.ClientMessage.DirectionOrBuilder getDirOrBuilder();
    }
    public static final class ShootDir extends
        com.google.protobuf.GeneratedMessage
        implements ShootDirOrBuilder {
      // Use ShootDir.newBuilder() to construct.
      private ShootDir(Builder builder) {
        super(builder);
      }
      private ShootDir(boolean noInit) {}
      
      private static final ShootDir defaultInstance;
      public static ShootDir getDefaultInstance() {
        return defaultInstance;
      }
      
      public ShootDir getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.jombies.server.Messages.internal_static_org_jombies_server_ClientMessage_ShootDir_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.jombies.server.Messages.internal_static_org_jombies_server_ClientMessage_ShootDir_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required .org.jombies.server.ClientMessage.Direction dir = 1;
      public static final int DIR_FIELD_NUMBER = 1;
      private org.jombies.server.Messages.ClientMessage.Direction dir_;
      public boolean hasDir() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.jombies.server.Messages.ClientMessage.Direction getDir() {
        return dir_;
      }
      public org.jombies.server.Messages.ClientMessage.DirectionOrBuilder getDirOrBuilder() {
        return dir_;
      }
      
      private void initFields() {
        dir_ = org.jombies.server.Messages.ClientMessage.Direction.getDefaultInstance();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasDir()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!getDir().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeMessage(1, dir_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, dir_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static org.jombies.server.Messages.ClientMessage.ShootDir parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.jombies.server.Messages.ClientMessage.ShootDir parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.jombies.server.Messages.ClientMessage.ShootDir parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static org.jombies.server.Messages.ClientMessage.ShootDir parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static org.jombies.server.Messages.ClientMessage.ShootDir parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.jombies.server.Messages.ClientMessage.ShootDir parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static org.jombies.server.Messages.ClientMessage.ShootDir parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.jombies.server.Messages.ClientMessage.ShootDir parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static org.jombies.server.Messages.ClientMessage.ShootDir parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static org.jombies.server.Messages.ClientMessage.ShootDir parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(org.jombies.server.Messages.ClientMessage.ShootDir prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements org.jombies.server.Messages.ClientMessage.ShootDirOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.jombies.server.Messages.internal_static_org_jombies_server_ClientMessage_ShootDir_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.jombies.server.Messages.internal_static_org_jombies_server_ClientMessage_ShootDir_fieldAccessorTable;
        }
        
        // Construct using org.jombies.server.Messages.ClientMessage.ShootDir.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getDirFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          if (dirBuilder_ == null) {
            dir_ = org.jombies.server.Messages.ClientMessage.Direction.getDefaultInstance();
          } else {
            dirBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.jombies.server.Messages.ClientMessage.ShootDir.getDescriptor();
        }
        
        public org.jombies.server.Messages.ClientMessage.ShootDir getDefaultInstanceForType() {
          return org.jombies.server.Messages.ClientMessage.ShootDir.getDefaultInstance();
        }
        
        public org.jombies.server.Messages.ClientMessage.ShootDir build() {
          org.jombies.server.Messages.ClientMessage.ShootDir result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private org.jombies.server.Messages.ClientMessage.ShootDir buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          org.jombies.server.Messages.ClientMessage.ShootDir result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public org.jombies.server.Messages.ClientMessage.ShootDir buildPartial() {
          org.jombies.server.Messages.ClientMessage.ShootDir result = new org.jombies.server.Messages.ClientMessage.ShootDir(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          if (dirBuilder_ == null) {
            result.dir_ = dir_;
          } else {
            result.dir_ = dirBuilder_.build();
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.jombies.server.Messages.ClientMessage.ShootDir) {
            return mergeFrom((org.jombies.server.Messages.ClientMessage.ShootDir)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(org.jombies.server.Messages.ClientMessage.ShootDir other) {
          if (other == org.jombies.server.Messages.ClientMessage.ShootDir.getDefaultInstance()) return this;
          if (other.hasDir()) {
            mergeDir(other.getDir());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasDir()) {
            
            return false;
          }
          if (!getDir().isInitialized()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                org.jombies.server.Messages.ClientMessage.Direction.Builder subBuilder = org.jombies.server.Messages.ClientMessage.Direction.newBuilder();
                if (hasDir()) {
                  subBuilder.mergeFrom(getDir());
                }
                input.readMessage(subBuilder, extensionRegistry);
                setDir(subBuilder.buildPartial());
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required .org.jombies.server.ClientMessage.Direction dir = 1;
        private org.jombies.server.Messages.ClientMessage.Direction dir_ = org.jombies.server.Messages.ClientMessage.Direction.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            org.jombies.server.Messages.ClientMessage.Direction, org.jombies.server.Messages.ClientMessage.Direction.Builder, org.jombies.server.Messages.ClientMessage.DirectionOrBuilder> dirBuilder_;
        public boolean hasDir() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public org.jombies.server.Messages.ClientMessage.Direction getDir() {
          if (dirBuilder_ == null) {
            return dir_;
          } else {
            return dirBuilder_.getMessage();
          }
        }
        public Builder setDir(org.jombies.server.Messages.ClientMessage.Direction value) {
          if (dirBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            dir_ = value;
            onChanged();
          } else {
            dirBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        public Builder setDir(
            org.jombies.server.Messages.ClientMessage.Direction.Builder builderForValue) {
          if (dirBuilder_ == null) {
            dir_ = builderForValue.build();
            onChanged();
          } else {
            dirBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        public Builder mergeDir(org.jombies.server.Messages.ClientMessage.Direction value) {
          if (dirBuilder_ == null) {
            if (((bitField0_ & 0x00000001) == 0x00000001) &&
                dir_ != org.jombies.server.Messages.ClientMessage.Direction.getDefaultInstance()) {
              dir_ =
                org.jombies.server.Messages.ClientMessage.Direction.newBuilder(dir_).mergeFrom(value).buildPartial();
            } else {
              dir_ = value;
            }
            onChanged();
          } else {
            dirBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000001;
          return this;
        }
        public Builder clearDir() {
          if (dirBuilder_ == null) {
            dir_ = org.jombies.server.Messages.ClientMessage.Direction.getDefaultInstance();
            onChanged();
          } else {
            dirBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }
        public org.jombies.server.Messages.ClientMessage.Direction.Builder getDirBuilder() {
          bitField0_ |= 0x00000001;
          onChanged();
          return getDirFieldBuilder().getBuilder();
        }
        public org.jombies.server.Messages.ClientMessage.DirectionOrBuilder getDirOrBuilder() {
          if (dirBuilder_ != null) {
            return dirBuilder_.getMessageOrBuilder();
          } else {
            return dir_;
          }
        }
        private com.google.protobuf.SingleFieldBuilder<
            org.jombies.server.Messages.ClientMessage.Direction, org.jombies.server.Messages.ClientMessage.Direction.Builder, org.jombies.server.Messages.ClientMessage.DirectionOrBuilder> 
            getDirFieldBuilder() {
          if (dirBuilder_ == null) {
            dirBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                org.jombies.server.Messages.ClientMessage.Direction, org.jombies.server.Messages.ClientMessage.Direction.Builder, org.jombies.server.Messages.ClientMessage.DirectionOrBuilder>(
                    dir_,
                    getParentForChildren(),
                    isClean());
            dir_ = null;
          }
          return dirBuilder_;
        }
        
        // @@protoc_insertion_point(builder_scope:org.jombies.server.ClientMessage.ShootDir)
      }
      
      static {
        defaultInstance = new ShootDir(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:org.jombies.server.ClientMessage.ShootDir)
    }
    
    private int bitField0_;
    // required .org.jombies.server.ClientMessage.MessageType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private org.jombies.server.Messages.ClientMessage.MessageType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.jombies.server.Messages.ClientMessage.MessageType getType() {
      return type_;
    }
    
    // optional .org.jombies.server.ClientMessage.ShootDir shootDie = 2;
    public static final int SHOOTDIE_FIELD_NUMBER = 2;
    private org.jombies.server.Messages.ClientMessage.ShootDir shootDie_;
    public boolean hasShootDie() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public org.jombies.server.Messages.ClientMessage.ShootDir getShootDie() {
      return shootDie_;
    }
    public org.jombies.server.Messages.ClientMessage.ShootDirOrBuilder getShootDieOrBuilder() {
      return shootDie_;
    }
    
    // optional .org.jombies.server.ClientMessage.ChangeDirMessage chDir = 3;
    public static final int CHDIR_FIELD_NUMBER = 3;
    private org.jombies.server.Messages.ClientMessage.ChangeDirMessage chDir_;
    public boolean hasChDir() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public org.jombies.server.Messages.ClientMessage.ChangeDirMessage getChDir() {
      return chDir_;
    }
    public org.jombies.server.Messages.ClientMessage.ChangeDirMessageOrBuilder getChDirOrBuilder() {
      return chDir_;
    }
    
    private void initFields() {
      type_ = org.jombies.server.Messages.ClientMessage.MessageType.CHANGE_DIR;
      shootDie_ = org.jombies.server.Messages.ClientMessage.ShootDir.getDefaultInstance();
      chDir_ = org.jombies.server.Messages.ClientMessage.ChangeDirMessage.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasShootDie()) {
        if (!getShootDie().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasChDir()) {
        if (!getChDir().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, shootDie_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, chDir_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, shootDie_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, chDir_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.jombies.server.Messages.ClientMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jombies.server.Messages.ClientMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jombies.server.Messages.ClientMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.jombies.server.Messages.ClientMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.jombies.server.Messages.ClientMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jombies.server.Messages.ClientMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.jombies.server.Messages.ClientMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.jombies.server.Messages.ClientMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.jombies.server.Messages.ClientMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.jombies.server.Messages.ClientMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.jombies.server.Messages.ClientMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.jombies.server.Messages.ClientMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.jombies.server.Messages.internal_static_org_jombies_server_ClientMessage_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.jombies.server.Messages.internal_static_org_jombies_server_ClientMessage_fieldAccessorTable;
      }
      
      // Construct using org.jombies.server.Messages.ClientMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getShootDieFieldBuilder();
          getChDirFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = org.jombies.server.Messages.ClientMessage.MessageType.CHANGE_DIR;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (shootDieBuilder_ == null) {
          shootDie_ = org.jombies.server.Messages.ClientMessage.ShootDir.getDefaultInstance();
        } else {
          shootDieBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (chDirBuilder_ == null) {
          chDir_ = org.jombies.server.Messages.ClientMessage.ChangeDirMessage.getDefaultInstance();
        } else {
          chDirBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.jombies.server.Messages.ClientMessage.getDescriptor();
      }
      
      public org.jombies.server.Messages.ClientMessage getDefaultInstanceForType() {
        return org.jombies.server.Messages.ClientMessage.getDefaultInstance();
      }
      
      public org.jombies.server.Messages.ClientMessage build() {
        org.jombies.server.Messages.ClientMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.jombies.server.Messages.ClientMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.jombies.server.Messages.ClientMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.jombies.server.Messages.ClientMessage buildPartial() {
        org.jombies.server.Messages.ClientMessage result = new org.jombies.server.Messages.ClientMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (shootDieBuilder_ == null) {
          result.shootDie_ = shootDie_;
        } else {
          result.shootDie_ = shootDieBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (chDirBuilder_ == null) {
          result.chDir_ = chDir_;
        } else {
          result.chDir_ = chDirBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.jombies.server.Messages.ClientMessage) {
          return mergeFrom((org.jombies.server.Messages.ClientMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.jombies.server.Messages.ClientMessage other) {
        if (other == org.jombies.server.Messages.ClientMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasShootDie()) {
          mergeShootDie(other.getShootDie());
        }
        if (other.hasChDir()) {
          mergeChDir(other.getChDir());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasShootDie()) {
          if (!getShootDie().isInitialized()) {
            
            return false;
          }
        }
        if (hasChDir()) {
          if (!getChDir().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.jombies.server.Messages.ClientMessage.MessageType value = org.jombies.server.Messages.ClientMessage.MessageType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              org.jombies.server.Messages.ClientMessage.ShootDir.Builder subBuilder = org.jombies.server.Messages.ClientMessage.ShootDir.newBuilder();
              if (hasShootDie()) {
                subBuilder.mergeFrom(getShootDie());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setShootDie(subBuilder.buildPartial());
              break;
            }
            case 26: {
              org.jombies.server.Messages.ClientMessage.ChangeDirMessage.Builder subBuilder = org.jombies.server.Messages.ClientMessage.ChangeDirMessage.newBuilder();
              if (hasChDir()) {
                subBuilder.mergeFrom(getChDir());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setChDir(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .org.jombies.server.ClientMessage.MessageType type = 1;
      private org.jombies.server.Messages.ClientMessage.MessageType type_ = org.jombies.server.Messages.ClientMessage.MessageType.CHANGE_DIR;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.jombies.server.Messages.ClientMessage.MessageType getType() {
        return type_;
      }
      public Builder setType(org.jombies.server.Messages.ClientMessage.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = org.jombies.server.Messages.ClientMessage.MessageType.CHANGE_DIR;
        onChanged();
        return this;
      }
      
      // optional .org.jombies.server.ClientMessage.ShootDir shootDie = 2;
      private org.jombies.server.Messages.ClientMessage.ShootDir shootDie_ = org.jombies.server.Messages.ClientMessage.ShootDir.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.jombies.server.Messages.ClientMessage.ShootDir, org.jombies.server.Messages.ClientMessage.ShootDir.Builder, org.jombies.server.Messages.ClientMessage.ShootDirOrBuilder> shootDieBuilder_;
      public boolean hasShootDie() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public org.jombies.server.Messages.ClientMessage.ShootDir getShootDie() {
        if (shootDieBuilder_ == null) {
          return shootDie_;
        } else {
          return shootDieBuilder_.getMessage();
        }
      }
      public Builder setShootDie(org.jombies.server.Messages.ClientMessage.ShootDir value) {
        if (shootDieBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          shootDie_ = value;
          onChanged();
        } else {
          shootDieBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setShootDie(
          org.jombies.server.Messages.ClientMessage.ShootDir.Builder builderForValue) {
        if (shootDieBuilder_ == null) {
          shootDie_ = builderForValue.build();
          onChanged();
        } else {
          shootDieBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeShootDie(org.jombies.server.Messages.ClientMessage.ShootDir value) {
        if (shootDieBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              shootDie_ != org.jombies.server.Messages.ClientMessage.ShootDir.getDefaultInstance()) {
            shootDie_ =
              org.jombies.server.Messages.ClientMessage.ShootDir.newBuilder(shootDie_).mergeFrom(value).buildPartial();
          } else {
            shootDie_ = value;
          }
          onChanged();
        } else {
          shootDieBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearShootDie() {
        if (shootDieBuilder_ == null) {
          shootDie_ = org.jombies.server.Messages.ClientMessage.ShootDir.getDefaultInstance();
          onChanged();
        } else {
          shootDieBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public org.jombies.server.Messages.ClientMessage.ShootDir.Builder getShootDieBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getShootDieFieldBuilder().getBuilder();
      }
      public org.jombies.server.Messages.ClientMessage.ShootDirOrBuilder getShootDieOrBuilder() {
        if (shootDieBuilder_ != null) {
          return shootDieBuilder_.getMessageOrBuilder();
        } else {
          return shootDie_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          org.jombies.server.Messages.ClientMessage.ShootDir, org.jombies.server.Messages.ClientMessage.ShootDir.Builder, org.jombies.server.Messages.ClientMessage.ShootDirOrBuilder> 
          getShootDieFieldBuilder() {
        if (shootDieBuilder_ == null) {
          shootDieBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.jombies.server.Messages.ClientMessage.ShootDir, org.jombies.server.Messages.ClientMessage.ShootDir.Builder, org.jombies.server.Messages.ClientMessage.ShootDirOrBuilder>(
                  shootDie_,
                  getParentForChildren(),
                  isClean());
          shootDie_ = null;
        }
        return shootDieBuilder_;
      }
      
      // optional .org.jombies.server.ClientMessage.ChangeDirMessage chDir = 3;
      private org.jombies.server.Messages.ClientMessage.ChangeDirMessage chDir_ = org.jombies.server.Messages.ClientMessage.ChangeDirMessage.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.jombies.server.Messages.ClientMessage.ChangeDirMessage, org.jombies.server.Messages.ClientMessage.ChangeDirMessage.Builder, org.jombies.server.Messages.ClientMessage.ChangeDirMessageOrBuilder> chDirBuilder_;
      public boolean hasChDir() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public org.jombies.server.Messages.ClientMessage.ChangeDirMessage getChDir() {
        if (chDirBuilder_ == null) {
          return chDir_;
        } else {
          return chDirBuilder_.getMessage();
        }
      }
      public Builder setChDir(org.jombies.server.Messages.ClientMessage.ChangeDirMessage value) {
        if (chDirBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          chDir_ = value;
          onChanged();
        } else {
          chDirBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setChDir(
          org.jombies.server.Messages.ClientMessage.ChangeDirMessage.Builder builderForValue) {
        if (chDirBuilder_ == null) {
          chDir_ = builderForValue.build();
          onChanged();
        } else {
          chDirBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeChDir(org.jombies.server.Messages.ClientMessage.ChangeDirMessage value) {
        if (chDirBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              chDir_ != org.jombies.server.Messages.ClientMessage.ChangeDirMessage.getDefaultInstance()) {
            chDir_ =
              org.jombies.server.Messages.ClientMessage.ChangeDirMessage.newBuilder(chDir_).mergeFrom(value).buildPartial();
          } else {
            chDir_ = value;
          }
          onChanged();
        } else {
          chDirBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearChDir() {
        if (chDirBuilder_ == null) {
          chDir_ = org.jombies.server.Messages.ClientMessage.ChangeDirMessage.getDefaultInstance();
          onChanged();
        } else {
          chDirBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public org.jombies.server.Messages.ClientMessage.ChangeDirMessage.Builder getChDirBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getChDirFieldBuilder().getBuilder();
      }
      public org.jombies.server.Messages.ClientMessage.ChangeDirMessageOrBuilder getChDirOrBuilder() {
        if (chDirBuilder_ != null) {
          return chDirBuilder_.getMessageOrBuilder();
        } else {
          return chDir_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          org.jombies.server.Messages.ClientMessage.ChangeDirMessage, org.jombies.server.Messages.ClientMessage.ChangeDirMessage.Builder, org.jombies.server.Messages.ClientMessage.ChangeDirMessageOrBuilder> 
          getChDirFieldBuilder() {
        if (chDirBuilder_ == null) {
          chDirBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.jombies.server.Messages.ClientMessage.ChangeDirMessage, org.jombies.server.Messages.ClientMessage.ChangeDirMessage.Builder, org.jombies.server.Messages.ClientMessage.ChangeDirMessageOrBuilder>(
                  chDir_,
                  getParentForChildren(),
                  isClean());
          chDir_ = null;
        }
        return chDirBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:org.jombies.server.ClientMessage)
    }
    
    static {
      defaultInstance = new ClientMessage(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.jombies.server.ClientMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jombies_server_ClientMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_jombies_server_ClientMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jombies_server_ClientMessage_Direction_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_jombies_server_ClientMessage_Direction_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jombies_server_ClientMessage_ChangeDirMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_jombies_server_ClientMessage_ChangeDirMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_jombies_server_ClientMessage_ShootDir_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_jombies_server_ClientMessage_ShootDir_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016messages.proto\022\022org.jombies.server\"\347\003\n" +
      "\rClientMessage\022;\n\004type\030\001 \002(\0162-.org.jombi" +
      "es.server.ClientMessage.MessageType\022<\n\010s" +
      "hootDie\030\002 \001(\0132*.org.jombies.server.Clien" +
      "tMessage.ShootDir\022A\n\005chDir\030\003 \001(\01322.org.j" +
      "ombies.server.ClientMessage.ChangeDirMes" +
      "sage\0329\n\tDirection\022\n\n\002dX\030\001 \002(\005\022\n\n\002dy\030\002 \002(" +
      "\005\022\t\n\001x\030\003 \002(\005\022\t\n\001y\030\004 \002(\005\032^\n\020ChangeDirMess" +
      "age\022\020\n\010isMoving\030\001 \002(\010\0228\n\003dir\030\002 \001(\0132+.org" +
      ".jombies.server.ClientMessage.Direction\032",
      "D\n\010ShootDir\0228\n\003dir\030\001 \002(\0132+.org.jombies.s" +
      "erver.ClientMessage.Direction\"7\n\013Message" +
      "Type\022\016\n\nCHANGE_DIR\020\001\022\t\n\005SHOOT\020\002\022\r\n\tRELOA" +
      "DING\020\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_jombies_server_ClientMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_jombies_server_ClientMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_jombies_server_ClientMessage_descriptor,
              new java.lang.String[] { "Type", "ShootDie", "ChDir", },
              org.jombies.server.Messages.ClientMessage.class,
              org.jombies.server.Messages.ClientMessage.Builder.class);
          internal_static_org_jombies_server_ClientMessage_Direction_descriptor =
            internal_static_org_jombies_server_ClientMessage_descriptor.getNestedTypes().get(0);
          internal_static_org_jombies_server_ClientMessage_Direction_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_jombies_server_ClientMessage_Direction_descriptor,
              new java.lang.String[] { "DX", "Dy", "X", "Y", },
              org.jombies.server.Messages.ClientMessage.Direction.class,
              org.jombies.server.Messages.ClientMessage.Direction.Builder.class);
          internal_static_org_jombies_server_ClientMessage_ChangeDirMessage_descriptor =
            internal_static_org_jombies_server_ClientMessage_descriptor.getNestedTypes().get(1);
          internal_static_org_jombies_server_ClientMessage_ChangeDirMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_jombies_server_ClientMessage_ChangeDirMessage_descriptor,
              new java.lang.String[] { "IsMoving", "Dir", },
              org.jombies.server.Messages.ClientMessage.ChangeDirMessage.class,
              org.jombies.server.Messages.ClientMessage.ChangeDirMessage.Builder.class);
          internal_static_org_jombies_server_ClientMessage_ShootDir_descriptor =
            internal_static_org_jombies_server_ClientMessage_descriptor.getNestedTypes().get(2);
          internal_static_org_jombies_server_ClientMessage_ShootDir_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_jombies_server_ClientMessage_ShootDir_descriptor,
              new java.lang.String[] { "Dir", },
              org.jombies.server.Messages.ClientMessage.ShootDir.class,
              org.jombies.server.Messages.ClientMessage.ShootDir.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
